# Generated by Django 3.0.5 on 2020-07-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0003_auto_20200715_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='legume',
            name='prix',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
